"""
Pydantic schemas for Synthesize.io API.

This module exports all schema classes for request validation
and response serialization.
"""

# Base schemas
from app.schemas.base import (
    BaseSchema,
    TimestampMixin,
    PaginatedResponse,
    MessageResponse,
    ErrorDetail,
    ErrorResponse,
    IDResponse,
    SuccessResponse,
)

# Authentication schemas
from app.schemas.auth import (
    RegisterRequest,
    LoginRequest,
    RefreshTokenRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    ChangePasswordRequest,
    VerifyEmailRequest,
    TokenResponse,
    AuthUserResponse,
    LoginResponse,
    RegisterResponse,
    SessionInfo,
    SessionListResponse,
)

# User schemas
from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserPreferencesUpdate,
    AdminUserUpdate,
    UserPreferences,
    UserResponse,
    UserDetailResponse,
    UserListResponse,
    UserStatsResponse,
    UserActivityItem,
    UserActivityResponse,
    PublicUserProfile,
)

# Organization schemas
from app.schemas.organization import (
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationSettingsUpdate,
    OrganizationSettings,
    OrganizationResponse,
    OrganizationDetailResponse,
    OrganizationListResponse,
    OrganizationMemberCreate,
    OrganizationInviteCreate,
    OrganizationMemberUpdate,
    OrganizationMemberResponse,
    OrganizationMemberListResponse,
    OrganizationInviteResponse,
    OrganizationInviteListResponse,
    AcceptInviteRequest,
    OrganizationStatsResponse,
    OrganizationUsageResponse,
)

# Subscription and billing schemas
from app.schemas.subscription import (
    PlanFeatures,
    SubscriptionPlanResponse,
    SubscriptionPlanListResponse,
    SubscriptionCreate,
    SubscriptionUpdate,
    SubscriptionResponse,
    SubscriptionDetailResponse,
    CheckoutRequest,
    CheckoutResponse,
    CheckoutCompleteRequest,
    PaymentResponse,
    PaymentListResponse,
    InvoiceLineItem,
    InvoiceResponse,
    InvoiceListResponse,
    CouponValidateRequest,
    CouponValidateResponse,
    BillingInfoUpdate,
    BillingInfoResponse,
    BillingPortalResponse,
    UsageSummaryResponse,
    UsageHistoryItem,
    UsageHistoryResponse,
)

# Dataset schemas
from app.schemas.dataset import (
    FieldConstraint,
    SchemaField,
    DatasetSchema,
    DatasetCreate,
    DatasetUpdate,
    DatasetSchemaUpdate,
    DatasetResponse,
    DatasetListResponse,
    DatasetDetailResponse,
    GenerationOptions,
    GenerationRequest,
    GenerationPreviewRequest,
    SchemaInferRequest,
    SchemaFromPromptRequest,
    GenerationJobResponse,
    GenerationJobListResponse,
    GenerationJobDetailResponse,
    DataPreviewResponse,
    DataSampleResponse,
    TemplateResponse,
    TemplateListResponse,
    TemplateCategoryResponse,
    TemplateCategoriesResponse,
    ImportSchemaRequest,
    ExportSchemaResponse,
    # Additional schemas for endpoints
    SchemaFieldCreate,
    SchemaFieldUpdate,
    SchemaFieldResponse,
    GenerationPreviewResponse,
    DatasetTemplateResponse,
)

# API Key schemas
from app.schemas.api_key import (
    APIKeyCreate,
    APIKeyUpdate,
    APIKeyRegenerateRequest,
    APIKeyResponse,
    APIKeyCreateResponse,
    APIKeyListResponse,
    APIKeyUsageItem,
    APIKeyUsageResponse,
    APIKeyValidationResponse,
)

# Webhook schemas
from app.schemas.webhook import (
    WebhookCreate,
    WebhookUpdate,
    WebhookResponse,
    WebhookListResponse,
    WebhookDeliveryResponse,
    WebhookDeliveryListResponse,
    WebhookTestRequest,
    WebhookTestResponse,
    WebhookEventPayload,
    JobWebhookPayload,
    DatasetWebhookPayload,
    UsageWebhookPayload,
    WebhookSignatureVerifyRequest,
    WebhookSignatureVerifyResponse,
)

# Admin schemas
from app.schemas.admin import (
    AdminDashboardStats,
    AdminChartDataPoint,
    AdminChartResponse,
    AdminUserCreate,
    AdminUserUpdate,
    AdminUserResponse,
    AdminUserListResponse,
    AdminUserDetailResponse,
    AdminSubscriptionUpdate,
    AdminSubscriptionResponse,
    AdminSubscriptionListResponse,
    AdminPlanCreate,
    AdminPlanUpdate,
    SystemConfigUpdate,
    SystemConfigResponse,
    SystemConfigListResponse,
    FeatureFlagCreate,
    FeatureFlagUpdate,
    FeatureFlagResponse,
    FeatureFlagListResponse,
    AuditLogResponse,
    AuditLogListResponse,
    AdminTicketResponse,
    AdminTicketListResponse,
    AdminTicketUpdate,
    AdminTicketReplyRequest,
    AdminJobResponse,
    AdminJobListResponse,
    AdminJobAction,
    ServiceHealth,
    SystemHealthResponse,
    BulkUserAction,
    BulkActionResponse,
)


__all__ = [
    # Base
    "BaseSchema",
    "TimestampMixin",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorDetail",
    "ErrorResponse",
    "IDResponse",
    "SuccessResponse",
    
    # Auth
    "RegisterRequest",
    "LoginRequest",
    "RefreshTokenRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "ChangePasswordRequest",
    "VerifyEmailRequest",
    "TokenResponse",
    "AuthUserResponse",
    "LoginResponse",
    "RegisterResponse",
    "SessionInfo",
    "SessionListResponse",
    
    # User
    "UserCreate",
    "UserUpdate",
    "UserPreferencesUpdate",
    "AdminUserUpdate",
    "UserPreferences",
    "UserResponse",
    "UserDetailResponse",
    "UserListResponse",
    "UserStatsResponse",
    "UserActivityItem",
    "UserActivityResponse",
    "PublicUserProfile",
    
    # Organization
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationSettingsUpdate",
    "OrganizationSettings",
    "OrganizationResponse",
    "OrganizationDetailResponse",
    "OrganizationListResponse",
    "OrganizationMemberCreate",
    "OrganizationInviteCreate",
    "OrganizationMemberUpdate",
    "OrganizationMemberResponse",
    "OrganizationMemberListResponse",
    "OrganizationInviteResponse",
    "OrganizationInviteListResponse",
    "AcceptInviteRequest",
    "OrganizationStatsResponse",
    "OrganizationUsageResponse",
    
    # Subscription
    "PlanFeatures",
    "SubscriptionPlanResponse",
    "SubscriptionPlanListResponse",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionResponse",
    "SubscriptionDetailResponse",
    "CheckoutRequest",
    "CheckoutResponse",
    "CheckoutCompleteRequest",
    "PaymentResponse",
    "PaymentListResponse",
    "InvoiceLineItem",
    "InvoiceResponse",
    "InvoiceListResponse",
    "CouponValidateRequest",
    "CouponValidateResponse",
    "BillingInfoUpdate",
    "BillingInfoResponse",
    "BillingPortalResponse",
    "UsageSummaryResponse",
    "UsageHistoryItem",
    "UsageHistoryResponse",
    
    # Dataset
    "FieldConstraint",
    "SchemaField",
    "DatasetSchema",
    "DatasetCreate",
    "DatasetUpdate",
    "DatasetSchemaUpdate",
    "DatasetResponse",
    "DatasetListResponse",
    "DatasetDetailResponse",
    "GenerationOptions",
    "GenerationRequest",
    "GenerationPreviewRequest",
    "SchemaInferRequest",
    "SchemaFromPromptRequest",
    "GenerationJobResponse",
    "GenerationJobListResponse",
    "GenerationJobDetailResponse",
    "DataPreviewResponse",
    "DataSampleResponse",
    "TemplateResponse",
    "TemplateListResponse",
    "TemplateCategoryResponse",
    "TemplateCategoriesResponse",
    "ImportSchemaRequest",
    "ExportSchemaResponse",
    
    # API Key
    "APIKeyCreate",
    "APIKeyUpdate",
    "APIKeyRegenerateRequest",
    "APIKeyResponse",
    "APIKeyCreateResponse",
    "APIKeyListResponse",
    "APIKeyUsageItem",
    "APIKeyUsageResponse",
    "APIKeyValidationResponse",
    
    # Webhook
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    "WebhookListResponse",
    "WebhookDeliveryResponse",
    "WebhookDeliveryListResponse",
    "WebhookTestRequest",
    "WebhookTestResponse",
    "WebhookEventPayload",
    "JobWebhookPayload",
    "DatasetWebhookPayload",
    "UsageWebhookPayload",
    "WebhookSignatureVerifyRequest",
    "WebhookSignatureVerifyResponse",
    
    # Admin
    "AdminDashboardStats",
    "AdminChartDataPoint",
    "AdminChartResponse",
    "AdminUserCreate",
    "AdminUserUpdate",
    "AdminUserResponse",
    "AdminUserListResponse",
    "AdminUserDetailResponse",
    "AdminSubscriptionUpdate",
    "AdminSubscriptionResponse",
    "AdminSubscriptionListResponse",
    "AdminPlanCreate",
    "AdminPlanUpdate",
    "SystemConfigUpdate",
    "SystemConfigResponse",
    "SystemConfigListResponse",
    "FeatureFlagCreate",
    "FeatureFlagUpdate",
    "FeatureFlagResponse",
    "FeatureFlagListResponse",
    "AuditLogResponse",
    "AuditLogListResponse",
    "AdminTicketResponse",
    "AdminTicketListResponse",
    "AdminTicketUpdate",
    "AdminTicketReplyRequest",
    "AdminJobResponse",
    "AdminJobListResponse",
    "AdminJobAction",
    "ServiceHealth",
    "SystemHealthResponse",
    "BulkUserAction",
    "BulkActionResponse",
]
