"""add_customer_queries_table

Revision ID: 2f6ec7d7e8bf
Revises: afa49047eb6d
Create Date: 2026-01-02 00:06:13.752974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f6ec7d7e8bf'
down_revision: Union[str, None] = 'afa49047eb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'READ', 'RESPONDED', 'CLOSED', name='querystatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_by_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queries_email', 'customer_queries', ['email'], unique=False)
    op.create_index('idx_queries_status_created', 'customer_queries', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_customer_queries_email'), 'customer_queries', ['email'], unique=False)
    op.create_index(op.f('ix_customer_queries_status'), 'customer_queries', ['status'], unique=False)
    op.alter_column('subscription_plans', 'price_inr_monthly',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription_plans', 'price_inr_annual',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'price_inr_annual',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscription_plans', 'price_inr_monthly',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_customer_queries_status'), table_name='customer_queries')
    op.drop_index(op.f('ix_customer_queries_email'), table_name='customer_queries')
    op.drop_index('idx_queries_status_created', table_name='customer_queries')
    op.drop_index('idx_queries_email', table_name='customer_queries')
    op.drop_table('customer_queries')
    # ### end Alembic commands ###
