"""dodo_payments_integration

Revision ID: a45430896294
Revises: 2f6ec7d7e8bf
Create Date: 2026-01-17 13:21:45.706869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a45430896294'
down_revision: Union[str, None] = '2f6ec7d7e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_contact_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('estimated_monthly_rows', sa.String(length=50), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('required_features', sa.JSON(), nullable=True),
    sa.Column('current_solution', sa.String(length=255), nullable=True),
    sa.Column('timeline', sa.String(length=50), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('how_heard_about_us', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'IN_PROGRESS', 'QUALIFIED', 'CLOSED_WON', 'CLOSED_LOST', name='enterprisecontactstatus'), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_value', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.Text(), nullable=True),
    sa.Column('converted_user_id', sa.UUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enterprise_requests_assigned', 'enterprise_contact_requests', ['assigned_to_id'], unique=False)
    op.create_index('idx_enterprise_requests_company', 'enterprise_contact_requests', ['company_name'], unique=False)
    op.create_index('idx_enterprise_requests_created', 'enterprise_contact_requests', ['created_at'], unique=False)
    op.create_index('idx_enterprise_requests_status', 'enterprise_contact_requests', ['status'], unique=False)
    op.create_index(op.f('ix_enterprise_contact_requests_email'), 'enterprise_contact_requests', ['email'], unique=False)
    op.create_index(op.f('ix_enterprise_contact_requests_status'), 'enterprise_contact_requests', ['status'], unique=False)
    op.alter_column('analytics_events', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('analytics_events', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    # Use raw SQL for ARRAY to JSON conversion
    op.execute("ALTER TABLE api_keys ALTER COLUMN scopes TYPE JSON USING array_to_json(scopes)")
    op.alter_column('api_keys', 'last_used_ip',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('api_request_logs', 'query_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('api_request_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('customer_queries', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('data_templates', 'schema_template',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('data_templates', 'default_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # Use raw SQL for ARRAY to JSON conversion
    op.execute("ALTER TABLE data_templates ALTER COLUMN tags TYPE JSON USING array_to_json(tags)")
    op.alter_column('dataset_downloads', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('datasets', 'schema_definition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('datasets', 'quality_issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # Drop GIN index before converting ARRAY to JSON (JSON type doesn't support GIN indexing)
    op.drop_index('idx_datasets_tags', table_name='datasets')
    # Use raw SQL for ARRAY to JSON conversion - array_to_json ensures proper JSON format
    op.execute("ALTER TABLE datasets ALTER COLUMN tags TYPE JSON USING array_to_json(tags)")
    # Note: Not recreating index as JSON type doesn't support standard indexing efficiently
    # Use raw SQL for ARRAY to JSON conversions in feature_flags
    op.execute("ALTER TABLE feature_flags ALTER COLUMN enabled_for_users TYPE JSON USING array_to_json(enabled_for_users)")
    op.execute("ALTER TABLE feature_flags ALTER COLUMN enabled_for_tiers TYPE JSON USING array_to_json(enabled_for_tiers)")
    op.alter_column('generation_jobs', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_requests', 'refined_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_requests', 'sample_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_requests', 'llm_response_raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_requests', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invoices', 'line_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('invoices', 'billing_address',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # Use raw SQL for ARRAY to JSON conversion
    op.execute("ALTER TABLE maintenance_windows ALTER COLUMN affected_services TYPE JSON USING array_to_json(affected_services)")
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'raw_user_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('organizations', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('payments', sa.Column('dodo_payment_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('dodo_customer_id', sa.String(length=255), nullable=True))
    op.alter_column('payments', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_payments_provider', table_name='payments')
    op.drop_index('ix_payments_external_payment_id', table_name='payments')
    op.create_index('idx_payments_dodo_id', 'payments', ['dodo_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_dodo_payment_id'), 'payments', ['dodo_payment_id'], unique=False)
    op.drop_column('payments', 'external_transaction_id')
    op.drop_column('payments', 'external_payment_id')
    op.alter_column('sessions', 'device_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('sessions', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.add_column('subscription_plans', sa.Column('dodo_product_id', sa.String(length=255), nullable=True))
    op.alter_column('subscription_plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('dodo_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('dodo_customer_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('dodo_product_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('is_enterprise', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('enterprise_contact_id', sa.UUID(), nullable=True))
    op.alter_column('subscriptions', 'custom_limits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('idx_subscriptions_dodo_id', 'subscriptions', ['dodo_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_dodo_customer_id'), 'subscriptions', ['dodo_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_dodo_subscription_id'), 'subscriptions', ['dodo_subscription_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'enterprise_contact_requests', ['enterprise_contact_id'], ['id'])
    op.drop_column('subscriptions', 'canceled_at')
    op.drop_column('subscriptions', 'external_subscription_id')
    op.alter_column('support_messages', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # Use raw SQL for ARRAY to JSON conversion
    op.execute("ALTER TABLE support_tickets ALTER COLUMN tags TYPE JSON USING array_to_json(tags)")
    op.alter_column('system_configs', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('users', 'last_login_ip',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('webhook_deliveries', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # Use raw SQL for ARRAY to JSON conversion
    op.execute("ALTER TABLE webhooks ALTER COLUMN events TYPE JSON USING array_to_json(events)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'events',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'last_login_ip',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('system_configs', 'value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('support_tickets', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('support_messages', 'attachments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('external_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_dodo_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_dodo_customer_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_dodo_id', table_name='subscriptions')
    op.alter_column('subscriptions', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('subscriptions', 'custom_limits',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('subscriptions', 'enterprise_contact_id')
    op.drop_column('subscriptions', 'is_enterprise')
    op.drop_column('subscriptions', 'dodo_product_id')
    op.drop_column('subscriptions', 'dodo_customer_id')
    op.drop_column('subscriptions', 'dodo_subscription_id')
    op.drop_column('subscriptions', 'cancelled_at')
    op.alter_column('subscription_plans', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('subscription_plans', 'dodo_product_id')
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('sessions', 'device_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('payments', sa.Column('external_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('external_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_dodo_payment_id'), table_name='payments')
    op.drop_index('idx_payments_dodo_id', table_name='payments')
    op.create_index('ix_payments_external_payment_id', 'payments', ['external_payment_id'], unique=False)
    op.create_index('idx_payments_provider', 'payments', ['provider', 'external_payment_id'], unique=False)
    op.alter_column('payments', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('payments', 'dodo_customer_id')
    op.drop_column('payments', 'dodo_payment_id')
    op.alter_column('organizations', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'raw_user_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('notifications', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('maintenance_windows', 'affected_services',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('invoices', 'billing_address',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('invoices', 'line_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_requests', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_requests', 'llm_response_raw',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_requests', 'sample_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_requests', 'refined_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_jobs', 'error_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('feature_flags', 'enabled_for_tiers',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('feature_flags', 'enabled_for_users',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    op.alter_column('datasets', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('datasets', 'quality_issues',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'schema_definition',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('dataset_downloads', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('data_templates', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('data_templates', 'default_settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('data_templates', 'schema_template',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('customer_queries', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('api_request_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('api_request_logs', 'query_params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('api_keys', 'last_used_ip',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('api_keys', 'scopes',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('analytics_events', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('analytics_events', 'properties',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_enterprise_contact_requests_status'), table_name='enterprise_contact_requests')
    op.drop_index(op.f('ix_enterprise_contact_requests_email'), table_name='enterprise_contact_requests')
    op.drop_index('idx_enterprise_requests_status', table_name='enterprise_contact_requests')
    op.drop_index('idx_enterprise_requests_created', table_name='enterprise_contact_requests')
    op.drop_index('idx_enterprise_requests_company', table_name='enterprise_contact_requests')
    op.drop_index('idx_enterprise_requests_assigned', table_name='enterprise_contact_requests')
    op.drop_table('enterprise_contact_requests')
    # ### end Alembic commands ###
