"""add active_organization_id to users

Revision ID: e614c1704282
Revises: 1e11615ac8fe
Create Date: 2026-01-22 04:58:15.806605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e614c1704282'
down_revision: Union[str, None] = '1e11615ac8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('min_amount_cents', sa.Integer(), nullable=True),
    sa.Column('applicable_plans', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coupons_active', 'coupons', ['is_active'], unique=False)
    op.create_index('idx_coupons_code', 'coupons', ['code'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('schema_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('llm_guidance', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', name='uq_schema_field_name')
    )
    op.create_index('idx_schema_fields_dataset', 'schema_fields', ['dataset_id'], unique=False)
    op.add_column('api_keys', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('api_keys', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('api_keys', sa.Column('ip_whitelist', sa.JSON(), nullable=True))
    op.add_column('api_keys', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('api_keys', sa.Column('last_used_ip', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # Skip GIN index on JSON column - not supported without JSONB
    # op.create_index('idx_datasets_tags', 'datasets', ['tags'], unique=False, postgresql_using='gin')
    op.add_column('generation_jobs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('generation_jobs', sa.Column('dataset_id', sa.UUID(), nullable=True))
    op.add_column('generation_jobs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('generation_jobs', sa.Column('output_format', sa.String(length=50), nullable=True))
    op.add_column('generation_jobs', sa.Column('generation_options', sa.JSON(), nullable=True))
    op.add_column('generation_jobs', sa.Column('progress', sa.Float(), nullable=True))
    op.add_column('generation_jobs', sa.Column('row_count', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('generation_jobs', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('generation_jobs', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('generation_jobs', sa.Column('llm_tokens_used', sa.Integer(), nullable=True))
    op.add_column('generation_jobs', sa.Column('credits_used', sa.Float(), nullable=True))
    op.alter_column('generation_jobs', 'request_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'generation_jobs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'generation_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'generation_jobs', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
    op.add_column('organization_invitations', sa.Column('status', sa.String(length=50), nullable=True, server_default='pending'))
    op.add_column('organization_invitations', sa.Column('token', sa.String(length=255), nullable=True))
    op.alter_column('organization_invitations', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('organizations', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('plan', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('subscription_plans', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('subscription_plans', sa.Column('price_monthly', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('price_yearly', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('limits', sa.JSON(), nullable=True))
    op.add_column('subscription_plans', sa.Column('is_recommended', sa.Boolean(), nullable=True))
    op.alter_column('subscription_plans', 'monthly_data_limit_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.add_column('users', sa.Column('active_organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['active_organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('webhooks', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('webhooks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('webhooks', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('retry_config', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('success_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'webhooks', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.drop_column('webhooks', 'success_count')
    op.drop_column('webhooks', 'retry_config')
    op.drop_column('webhooks', 'headers')
    op.drop_column('webhooks', 'description')
    op.drop_column('webhooks', 'organization_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_organization_id')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.alter_column('subscription_plans', 'monthly_data_limit_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('subscription_plans', 'is_recommended')
    op.drop_column('subscription_plans', 'limits')
    op.drop_column('subscription_plans', 'price_yearly')
    op.drop_column('subscription_plans', 'price_monthly')
    op.drop_column('subscription_plans', 'slug')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'plan')
    op.drop_column('organizations', 'size')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'billing_email')
    op.alter_column('organization_invitations', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('organization_invitations', 'token')
    op.drop_column('organization_invitations', 'status')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.alter_column('generation_jobs', 'request_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('generation_jobs', 'credits_used')
    op.drop_column('generation_jobs', 'llm_tokens_used')
    op.drop_column('generation_jobs', 'llm_model')
    op.drop_column('generation_jobs', 'file_size')
    op.drop_column('generation_jobs', 'file_path')
    op.drop_column('generation_jobs', 'row_count')
    op.drop_column('generation_jobs', 'progress')
    op.drop_column('generation_jobs', 'generation_options')
    op.drop_column('generation_jobs', 'output_format')
    op.drop_column('generation_jobs', 'organization_id')
    op.drop_column('generation_jobs', 'dataset_id')
    op.drop_column('generation_jobs', 'user_id')
    op.drop_index('idx_datasets_tags', table_name='datasets', postgresql_using='gin')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'last_used_ip')
    op.drop_column('api_keys', 'is_active')
    op.drop_column('api_keys', 'ip_whitelist')
    op.drop_column('api_keys', 'description')
    op.drop_column('api_keys', 'organization_id')
    op.drop_index('idx_schema_fields_dataset', table_name='schema_fields')
    op.drop_table('schema_fields')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index('idx_coupons_code', table_name='coupons')
    op.drop_index('idx_coupons_active', table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
